// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infracstructure.Data;

#nullable disable

namespace WhiteLagoon.Infracstructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250908142733_AddMoreVillaData")]
    partial class AddMoreVillaData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Villa 1 Description",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Villa 1",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            ID = 2,
                            Description = "Villa 2 Description",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Villa 2",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550
                        },
                        new
                        {
                            ID = 3,
                            Description = "Villa 3 Description",
                            ImageUrl = "https://placehold.co/600x403",
                            Name = "Villa 3",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        },
                        new
                        {
                            ID = 4,
                            Description = "Villa 4 Description",
                            ImageUrl = "https://placehold.co/600x404",
                            Name = "Villa 4",
                            Occupancy = 6,
                            Price = 500.0,
                            Sqft = 900
                        },
                        new
                        {
                            ID = 5,
                            Description = "Villa 5 Description",
                            ImageUrl = "https://placehold.co/600x405",
                            Name = "Villa 5",
                            Occupancy = 5,
                            Price = 350.0,
                            Sqft = 800
                        },
                        new
                        {
                            ID = 6,
                            Description = "Villa 6 Description",
                            ImageUrl = "https://placehold.co/600x406",
                            Name = "Villa 6",
                            Occupancy = 8,
                            Price = 600.0,
                            Sqft = 1000
                        },
                        new
                        {
                            ID = 7,
                            Description = "Villa 7 Description",
                            ImageUrl = "https://placehold.co/600x407",
                            Name = "Villa 7",
                            Occupancy = 4,
                            Price = 450.0,
                            Sqft = 700
                        },
                        new
                        {
                            ID = 8,
                            Description = "Villa 8 Description",
                            ImageUrl = "https://placehold.co/600x408",
                            Name = "Villa 8",
                            Occupancy = 6,
                            Price = 550.0,
                            Sqft = 850
                        },
                        new
                        {
                            ID = 9,
                            Description = "Villa 9 Description",
                            ImageUrl = "https://placehold.co/600x409",
                            Name = "Villa 9",
                            Occupancy = 4,
                            Price = 350.0,
                            Sqft = 600
                        },
                        new
                        {
                            ID = 10,
                            Description = "Villa 10 Description",
                            ImageUrl = "https://placehold.co/600x410",
                            Name = "Villa 10",
                            Occupancy = 5,
                            Price = 400.0,
                            Sqft = 700
                        },
                        new
                        {
                            ID = 11,
                            Description = "Villa 11 Description",
                            ImageUrl = "https://placehold.co/600x411",
                            Name = "Villa 11",
                            Occupancy = 7,
                            Price = 650.0,
                            Sqft = 950
                        },
                        new
                        {
                            ID = 12,
                            Description = "Villa 12 Description",
                            ImageUrl = "https://placehold.co/600x412",
                            Name = "Villa 12",
                            Occupancy = 6,
                            Price = 500.0,
                            Sqft = 800
                        },
                        new
                        {
                            ID = 13,
                            Description = "Villa 13 Description",
                            ImageUrl = "https://placehold.co/600x413",
                            Name = "Villa 13",
                            Occupancy = 8,
                            Price = 700.0,
                            Sqft = 1200
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("Special_Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaID")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaID");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            VillaID = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            VillaID = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            VillaID = 2
                        },
                        new
                        {
                            Villa_Number = 104,
                            VillaID = 2
                        },
                        new
                        {
                            Villa_Number = 105,
                            VillaID = 3
                        },
                        new
                        {
                            Villa_Number = 106,
                            VillaID = 3
                        },
                        new
                        {
                            Villa_Number = 107,
                            VillaID = 3
                        },
                        new
                        {
                            Villa_Number = 108,
                            VillaID = 3
                        },
                        new
                        {
                            Villa_Number = 109,
                            VillaID = 3
                        },
                        new
                        {
                            Villa_Number = 110,
                            VillaID = 3
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
