// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229142052_addProductAndSeedTable")]
    partial class addProductAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryName = "Test",
                            Description = "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...",
                            ImageURL = "https://placehold.co/600x400/png",
                            Name = "Prod1",
                            Price = 99.989999999999995
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryName = "Test",
                            Description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
                            ImageURL = "https://placehold.co/600x400/png",
                            Name = "Prod2",
                            Price = 149.5
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryName = "Test",
                            Description = "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium.",
                            ImageURL = "https://placehold.co/600x400/png",
                            Name = "Prod3",
                            Price = 59.990000000000002
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryName = "Test",
                            Description = "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus.",
                            ImageURL = "https://placehold.co/600x400/png",
                            Name = "Prod4",
                            Price = 199.0
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryName = "Test",
                            Description = "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet.",
                            ImageURL = "https://placehold.co/600x400/png",
                            Name = "Prod5",
                            Price = 29.949999999999999
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryName = "Test",
                            Description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae.",
                            ImageURL = "https://placehold.co/600x400/png",
                            Name = "Prod6",
                            Price = 89.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
